// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuPpnf5JSpoQY41YPHzW7ek-r5zUPC-Rc',
    appId: '1:79659647656:web:54a5f026c2f464d44a789d',
    messagingSenderId: '79659647656',
    projectId: 'jihccoin',
    authDomain: 'jihccoin.firebaseapp.com',
    storageBucket: 'jihccoin.firebasestorage.app',
    measurementId: 'G-FC2Q69EEQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_USdC2tf0I81SOnBBEsre6ap1AHe5dxY',
    appId: '1:79659647656:android:9ab057976629c29d4a789d',
    messagingSenderId: '79659647656',
    projectId: 'jihccoin',
    storageBucket: 'jihccoin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8gJ5RIL8IDgPn9WGTrZjGB5BV61wa1s',
    appId: '1:79659647656:ios:9a436e98bfacccaf4a789d',
    messagingSenderId: '79659647656',
    projectId: 'jihccoin',
    storageBucket: 'jihccoin.firebasestorage.app',
    iosBundleId: 'com.example.jihcCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8gJ5RIL8IDgPn9WGTrZjGB5BV61wa1s',
    appId: '1:79659647656:ios:9a436e98bfacccaf4a789d',
    messagingSenderId: '79659647656',
    projectId: 'jihccoin',
    storageBucket: 'jihccoin.firebasestorage.app',
    iosBundleId: 'com.example.jihcCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuPpnf5JSpoQY41YPHzW7ek-r5zUPC-Rc',
    appId: '1:79659647656:web:a740a17454af12184a789d',
    messagingSenderId: '79659647656',
    projectId: 'jihccoin',
    authDomain: 'jihccoin.firebaseapp.com',
    storageBucket: 'jihccoin.firebasestorage.app',
    measurementId: 'G-XJHXZY525X',
  );
}
